feat: mvp
broxus/nekoton_webview pull request #1
Opened 2023-05-16 10:39 UTC by Odrin

## Status

**READY/IN DEVELOPMENT/HOLD**

## Description

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

2023-05-22 10:22 UTC, nesquikm commented
I think we should drop "counter" feature (example/lib/counter)

2023-05-22 10:53 UTC, nesquikm requested changes

2023-05-22 10:53 UTC, nesquikm commented on example/lib/webview/view/webview_page.dart
> +  dynamic _getProviderState() => {
I think Map<String, Object> will be better than just a dynamic.

2023-05-22 10:53 UTC, nesquikm commented on example/lib/webview/view/webview_page.dart
> +  dynamic _requestPermissions() => {
Map<String, Object> will be better.

2023-05-22 10:53 UTC, nesquikm commented on example/lib/webview/view/webview_page.dart
> +                  case 'getProviderState':
It's better to make an enum and use it's name as string here. For example Methods.getProviderState.name.

2023-05-22 10:53 UTC, nesquikm commented on .gitignore
> +node_modules
No newline at eof.

2023-05-22 10:53 UTC, nesquikm commented on example/android/build.gradle
> +tasks.register("clean", Delete) {
I don't get it. Could you please comment on this?

2023-05-22 10:53 UTC, nesquikm commented on lib/src/nekoton_webview.dart
> +      callback: (List<dynamic> arguments) {
It's better to create a clear interface by providing an abstract class in the library and forcing user to pass an instance of inherited class here. Thus, the library user will have to implement the required methods with the necessary arguments, and also receive documentation for each of them (yeah, docs please?).

2023-05-22 12:26 UTC, Alex-A4 approved these changes

2023-05-30 09:32 UTC, nesquikm approved these changes

2023-05-30 09:32 UTC, nesquikm commented on melos.yaml
> +  generate-dart:
Can we merge generate-dart with codegen?

2023-05-30 09:40 UTC, merged